#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/tangorpro

PRODUCT_COPY_FILES += \
    vendor/google/tangorpro/proprietary/product/etc/ambient/matcher_tah.leveldb:$(TARGET_COPY_OUT_PRODUCT)/etc/ambient/matcher_tah.leveldb \
    vendor/google/tangorpro/proprietary/product/etc/appcompat/compat_framework_overrides.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/appcompat/compat_framework_overrides.xml \
    vendor/google/tangorpro/proprietary/product/etc/default-permissions/default-permissions_SmartDisplayPrebuilt.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permissions_SmartDisplayPrebuilt.xml \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.descriptor:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.descriptor \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.sound_model:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.sound_model \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.sound_model_2:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.sound_model_2 \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.sound_model_tflite:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.sound_model_tflite \
    vendor/google/tangorpro/proprietary/product/etc/permissions/androidx.camera.extensions.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/androidx.camera.extensions.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.android.apps.mediashell.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.apps.mediashell.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.android.apps.nest.castauth.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.apps.nest.castauth.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.android.apps.nest.dockmanager.app.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.apps.nest.dockmanager.app.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.assistant.hubui.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.assistant.hubui.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.pixel.camera.connectivity.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.pixel.camera.connectivity.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.pixel.camera.services.cameraidremapper.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.pixel.camera.services.cameraidremapper.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/privapp-permissions-google-p-lineage.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google-p-lineage.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/GoogleCamera_6gb_or_more_ram.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/GoogleCamera_6gb_or_more_ram.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/communal.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/communal.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/google-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-hiddenapi-package-whitelist.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/google-nest-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-nest-hiddenapi-package-whitelist.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/kids_home_experience.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/kids_home_experience.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/nexus.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/nexus.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_docking_experience_2022.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_docking_experience_2022.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2017.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2017.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2018.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2018.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2019.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2019.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2019_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2019_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2020.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2020.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2020_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2020_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2021.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2021.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2021_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2021_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2022.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2022.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2022_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2022_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_tablet_experience_2023.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_tablet_experience_2023.xml \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw.bin \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_csot.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_csot.bin \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp.bin \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_mp_csot.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp_csot.bin \
    vendor/google/tangorpro/proprietary/system_ext/etc/init/init.gs_watchdogd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.gs_watchdogd.rc \
    vendor/google/tangorpro/proprietary/system_ext/etc/init/vendor.google.edgetpu_app_service@1.0-service.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/vendor.google.edgetpu_app_service@1.0-service.rc \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.android.camera.extensions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.android.camera.extensions.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.android.camerax.extensions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.android.camerax.extensions.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.pixel.camera.connectivity.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.pixel.camera.connectivity.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.pixel.camera.services.cameraidremapper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.pixel.camera.services.cameraidremapper.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/google-ril.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/google-ril.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/privapp-permissions-google-se-lineage.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-google-se-lineage.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/privapp-permissions-qorvo.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-qorvo.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/public.libraries-google.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/public.libraries-google.txt

PRODUCT_PACKAGES += \
    com.google.edgetpu_app_service-V3-ndk \
    com.google.edgetpu_vendor_service-V2-ndk \
    libhbmsvmanager_jni \
    AndroidMediaShell \
    CastAuthPrebuilt \
    DeviceIntelligenceNetworkPrebuilt-astrea_20240329.00_RC02 \
    DevicePersonalizationPrebuiltPixelTablet2023-playstore_aiai_20250306.00_RC10 \
    DockManagerPrebuilt \
    HomegraphPrebuilt \
    HotwordEnrollmentOKGoogleFUSIONPro \
    HotwordEnrollmentXGoogleFUSIONPro \
    PixelCameraServices \
    SmartDisplayPrebuilt \
    UsoniaPrebuilt \
    PersistentBackgroundCameraServices \
    ConnectivityThermalPowerManager \
    DockSetup \
    HbmSVManager \
    UwbVendorService \
    grilservice \
    libhwinfo \
    com.android.hotwordenrollment.common.util \
    com.google.android.camera.extensions \
    com.google.android.camerax.extensions \
    com.google.pixel.camera.connectivity \
    com.google.pixel.camera.services.cameraidremapper \
    com.google.pixel.camera.services.lyricconfigprovider \
    google-ril \
    aocx_framework_compatibility_matrix_system_ext \
    imageprocessing_hal_framework_compatibility_matrix_system_ext \
    com.google.pixel.camera.services@1.0-service-google.xml \
    vendor.google.edgetpu_app_service@1.0-service.xml \
    gs_watchdogd \
    vendor.google.edgetpu_app_service@1.0-service

PRODUCT_PACKAGES += \
    system_ext_priv-app_HbmSVManager_lib_arm64_libhbmsvmanager_jni_so

PRODUCT_COPY_FILES += \
    vendor/google/tangorpro/proprietary/vendor/etc/Khronos/OpenCL/vendors/ARM.icd:$(TARGET_COPY_OUT_VENDOR)/etc/Khronos/OpenCL/vendors/ARM.icd \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/BLUETOOTH.dat:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/BLUETOOTH.dat \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/HANDSET.dat:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/HANDSET.dat \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/HANDSFREE.dat:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/HANDSFREE.dat \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/HEADSET.dat:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/HEADSET.dat \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/downlink_bluetooth_headset_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/downlink_bluetooth_headset_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/downlink_dock_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/downlink_dock_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/downlink_external_speaker_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/downlink_external_speaker_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/downlink_handset_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/downlink_handset_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/downlink_speaker_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/downlink_speaker_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/downlink_wired_headset_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/downlink_wired_headset_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/mcps.dat:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/mcps.dat \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/recording.gatf:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/recording.gatf \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/smartfeature.gstf:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/smartfeature.gstf \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_bluetooth_headset_aec_off_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_bluetooth_headset_aec_off_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_bluetooth_headset_aec_on_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_bluetooth_headset_aec_on_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_dock_aec_off_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_dock_aec_off_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_dock_aec_on_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_dock_aec_on_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_external_speaker_aec_off_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_external_speaker_aec_off_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_external_speaker_aec_on_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_external_speaker_aec_on_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_handset_aec_off_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_handset_aec_off_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_handset_aec_on_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_handset_aec_on_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_speaker_aec_off_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_speaker_aec_off_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_speaker_aec_on_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_speaker_aec_on_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_wired_headset_aec_off_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_wired_headset_aec_off_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/uplink_wired_headset_aec_on_config.pb:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/uplink_wired_headset_aec_on_config.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/waveform_aec_graph.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/waveform_aec_graph.tflite \
    vendor/google/tangorpro/proprietary/vendor/etc/atc_profile.json:$(TARGET_COPY_OUT_VENDOR)/etc/atc_profile.json \
    vendor/google/tangorpro/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/audio_platform_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_configuration.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/audio_policy_configuration_a2dp_offload_disabled.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_a2dp_offload_disabled.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_bluetooth_legacy_hal.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/bluetooth_audio_policy_configuration_7_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_audio_policy_configuration_7_0.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/bluetooth_power_limits.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits.csv \
    vendor/google/tangorpro/proprietary/vendor/etc/bluetooth_power_limits_GTU8P_CA.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_GTU8P_CA.csv \
    vendor/google/tangorpro/proprietary/vendor/etc/bluetooth_power_limits_GTU8P_EU.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_GTU8P_EU.csv \
    vendor/google/tangorpro/proprietary/vendor/etc/bluetooth_power_limits_GTU8P_JP.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_GTU8P_JP.csv \
    vendor/google/tangorpro/proprietary/vendor/etc/bluetooth_power_limits_GTU8P_US.csv:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_power_limits_GTU8P_US.csv \
    vendor/google/tangorpro/proprietary/vendor/etc/cert-chain.crt:$(TARGET_COPY_OUT_VENDOR)/etc/cert-chain.crt \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/activity.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/activity.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/activity.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/activity.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/ambient_volume.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ambient_volume.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/ambient_volume.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ambient_volume.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/capo.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/capo.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/capo.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/capo.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/drop.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/drop.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/drop.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/drop.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/health.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/health.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/health.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/health.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/imu_cal.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/imu_cal.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/imu_cal.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/imu_cal.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/libchre_log_database.bin:$(TARGET_COPY_OUT_VENDOR)/etc/chre/libchre_log_database.bin \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/motiondetector.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/motiondetector.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/motiondetector.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/motiondetector.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/sd.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sd.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/sd.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sd.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/system_signal_hub.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/system_signal_hub.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/system_signal_hub.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/system_signal_hub.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/uv_exposure.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/uv_exposure.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/uv_exposure.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/uv_exposure.so \
    vendor/google/tangorpro/proprietary/vendor/etc/display_colordata_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_colordata_cal0.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/display_golden_boe-ts110f5mlg0-rt4_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_golden_boe-ts110f5mlg0-rt4_cal0.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/display_golden_csot-ppa957db2d-rt4_cal0.pb:$(TARGET_COPY_OUT_VENDOR)/etc/display_golden_csot-ppa957db2d-rt4_cal0.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/display_settings.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_settings.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/displayconfig/display_id_4619827677550801152.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4619827677550801152.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/fstab.persist:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.persist \
    vendor/google/tangorpro/proprietary/vendor/etc/init.common.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.common.cfg \
    vendor/google/tangorpro/proprietary/vendor/etc/init/Exynos_C2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/Exynos_C2.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.authsecret-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.authsecret-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service.synabtlinux.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service.synabtlinux.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.camera.provider@2.7-service-google-apex.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.7-service-google-apex.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.contexthub-service.generic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.contexthub-service.generic.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.drm-service.castkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.castkey.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.dumpstate.3-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.dumpstate.3-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.edgetpu.logging@service-edgetpu-logging.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.edgetpu.logging@service-edgetpu-logging.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.graphics.allocator2-aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator2-aidl-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.gxp.logging@service-gxp-logging.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gxp.logging@service-gxp-logging.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.input.processor-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.input.processor-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.neuralnetworks@service-darwinn-aidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@service-darwinn-aidl.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.oemlock-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.oemlock-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.power.stats-service.pixel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.power.stats-service.pixel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.rlsservice-service-google-apex.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.rlsservice-service-google-apex.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.security.keymint-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.weaver-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.weaver-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/aocd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/aocd.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/aocxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/aocxd.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/citadeld.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/citadeld.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/com.google.edgetpu.tachyon-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.google.edgetpu.tachyon-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/fingerprint-fpc42.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fingerprint-fpc42.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/google.hardware.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/google.hardware.media.c2@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/hw/init.gs201.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.gs201.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/hw/init.gs201.storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.gs201.storage.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/hw/init.gs201.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.gs201.usb.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/hw/init.tangorpro.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.tangorpro.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/hwc3-pixel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hwc3-pixel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.aoc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.aoc.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.camera.set-interrupts-ownership.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.camera.set-interrupts-ownership.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.fingerprint.dump.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fingerprint.dump.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.module.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.module.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.pixel-mm-gs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.pixel-mm-gs.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.pixel-perf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.pixel-perf.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.sscoredump.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sscoredump.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.storage.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.touch.gti0.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.touch.gti0.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.touch.predump.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.touch.predump.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.usf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.usf.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init_dauntless.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_dauntless.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/libg3a_gabc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/libg3a_gabc.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/libg3a_gaf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/libg3a_gaf.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/libg3a_ghawb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/libg3a_ghawb.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/memtrack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/pixelstats-vendor.gs201.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixelstats-vendor.gs201.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/qorvo.uwb-calib.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qorvo.uwb-calib.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/qorvo.uwb-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qorvo.uwb-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/samsung.hardware.media.c2@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/samsung.hardware.media.c2@1.2-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/storage.gs201.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/storage.gs201.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/trusty_metricsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusty_metricsd.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/twoshay.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/twoshay.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.dolby.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.audiometricext@1.0-service-vendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.audiometricext@1.0-service-vendor.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.battery_mitigation-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.battery_mitigation-default.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.edgetpu_vendor_service@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.edgetpu_vendor_service@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.google_battery-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.google_battery-default.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.radioext@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.radioext@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/input_classifier_model.pb:$(TARGET_COPY_OUT_VENDOR)/etc/input_classifier_model.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/led_golden_calibration_LUT_black_CG.txt:$(TARGET_COPY_OUT_VENDOR)/etc/led_golden_calibration_LUT_black_CG.txt \
    vendor/google/tangorpro/proprietary/vendor/etc/led_golden_calibration_LUT_white_CG.txt:$(TARGET_COPY_OUT_VENDOR)/etc/led_golden_calibration_LUT_white_CG.txt \
    vendor/google/tangorpro/proprietary/vendor/etc/libg3a_standalone_gabc_rc:$(TARGET_COPY_OUT_VENDOR)/etc/libg3a_standalone_gabc_rc \
    vendor/google/tangorpro/proprietary/vendor/etc/libg3a_standalone_gaf_rc:$(TARGET_COPY_OUT_VENDOR)/etc/libg3a_standalone_gaf_rc \
    vendor/google/tangorpro/proprietary/vendor/etc/libg3a_standalone_ghawb_rc:$(TARGET_COPY_OUT_VENDOR)/etc/libg3a_standalone_ghawb_rc \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs_aosp_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_aosp_c2.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs_dolby_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_c2.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs_performance_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_c2.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/Pixel_Default_metrics.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem/Pixel_Default_metrics.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/Pixel_stability.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/modem/Pixel_stability.cfg \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/Pixel_stability.nprf:$(TARGET_COPY_OUT_VENDOR)/etc/modem/Pixel_stability.nprf \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/camera_front_mipi_coex_table.csv:$(TARGET_COPY_OUT_VENDOR)/etc/modem/camera_front_mipi_coex_table.csv \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/camera_rear_main_mipi_coex_table.csv:$(TARGET_COPY_OUT_VENDOR)/etc/modem/camera_rear_main_mipi_coex_table.csv \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/default.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/modem/default.cfg \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/default.nprf:$(TARGET_COPY_OUT_VENDOR)/etc/modem/default.nprf \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/default_metrics.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem/default_metrics.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/modem/logging.conf:$(TARGET_COPY_OUT_VENDOR)/etc/modem/logging.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/modem_stat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/modem_stat.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/permissions/android.hardware.strongbox_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.strongbox_keystore.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/permissions/com.google.android.camera.experimental2022.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.google.android.camera.experimental2022.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/permissions/com.google.android.hardwareinfo.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.google.android.hardwareinfo.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/permissions/vendor.android.hardware.camera.preview-dis.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.android.hardware.camera.preview-dis.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/pixelstats_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/pixelstats_config.json \
    vendor/google/tangorpro/proprietary/vendor/etc/powerhint.json:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.json \
    vendor/google/tangorpro/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/google/tangorpro/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base.policy \
    vendor/google/tangorpro/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext.policy \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/device_cal_info:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/device_cal_info \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/append/motion_state.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/append/motion_state.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/append/power.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/append/power.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/tangorpro_black.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/tangorpro_black.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/tangorpro_white.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/tangorpro_white.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/sound_trigger_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_configuration.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/google/tangorpro/proprietary/vendor/etc/thermal_info_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config.json \
    vendor/google/tangorpro/proprietary/vendor/etc/thermal_info_config_charge.json:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_info_config_charge.json \
    vendor/google/tangorpro/proprietary/vendor/etc/touchflow.pb:$(TARGET_COPY_OUT_VENDOR)/etc/touchflow.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/twoshay_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/twoshay_config.json \
    vendor/google/tangorpro/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-am.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-am.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-at.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-at.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-az.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-az.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-be.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-be.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-bg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-bg.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-by.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-by.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ca.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ca.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ch.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ch.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-cy.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-cy.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-cz.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-cz.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-de.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-de.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-default.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-dk.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-dk.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ee.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ee.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-es.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-es.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-fi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-fi.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-fr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-fr.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-gb.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-gb.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-gr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-gr.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-hr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-hr.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-hu.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-hu.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-id.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-id.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ie.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ie.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-is.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-is.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-it.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-it.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-jp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-jp.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-kg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-kg.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-kz.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-kz.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-li.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-li.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-lt.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-lt.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-lu.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-lu.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-lv.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-lv.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-mt.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-mt.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ni.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ni.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-nl.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-nl.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-no.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-no.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-np.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-np.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-pl.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-pl.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-pt.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-pt.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ro.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ro.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ru.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ru.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-se.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-se.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-si.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-si.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-sk.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-sk.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-tj.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-tj.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-tm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-tm.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-tw.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-tw.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-ua.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-ua.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-unknown.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-unknown.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-us.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-us.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration-uz.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration-uz.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/UWB-calibration.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/UWB-calibration.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/calib_paths:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/calib_paths \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/libuwb-uci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/libuwb-uci.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/waves_config.ini:$(TARGET_COPY_OUT_VENDOR)/etc/waves_config.ini \
    vendor/google/tangorpro/proprietary/vendor/etc/waves_preset.mps:$(TARGET_COPY_OUT_VENDOR)/etc/waves_preset.mps \
    vendor/google/tangorpro/proprietary/vendor/etc/wifi/coex_table.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/coex_table.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/google/tangorpro/proprietary/vendor/firmware/1540.app:$(TARGET_COPY_OUT_VENDOR)/firmware/1540.app \
    vendor/google/tangorpro/proprietary/vendor/firmware/L2-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L2-cs35l41-dsp1-spk-cali.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/L2-cs35l41-dsp1-spk-diag.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L2-cs35l41-dsp1-spk-diag.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/L2-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L2-cs35l41-dsp1-spk-prot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/R-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l41-dsp1-spk-cali.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/R-cs35l41-dsp1-spk-diag.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l41-dsp1-spk-diag.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/R-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l41-dsp1-spk-prot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/R2-cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R2-cs35l41-dsp1-spk-cali.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/R2-cs35l41-dsp1-spk-diag.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R2-cs35l41-dsp1-spk-diag.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/R2-cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R2-cs35l41-dsp1-spk-prot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/aoc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aoc.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/bcmdhd.cal:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd.cal \
    vendor/google/tangorpro/proprietary/vendor/firmware/bcmdhd_clm.blob:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_clm.blob \
    vendor/google/tangorpro/proprietary/vendor/firmware/cast_auth.app:$(TARGET_COPY_OUT_VENDOR)/firmware/cast_auth.app \
    vendor/google/tangorpro/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.wmfw \
    vendor/google/tangorpro/proprietary/vendor/firmware/cs35l41-dsp1-spk-diag.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-diag.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/cs35l41-dsp1-spk-diag.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-diag.wmfw \
    vendor/google/tangorpro/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.wmfw \
    vendor/google/tangorpro/proprietary/vendor/firmware/dauntless/d3m2.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dauntless/d3m2.ec.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/dauntless/evt.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dauntless/evt.ec.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/dauntless/proto11.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dauntless/proto11.ec.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/filter_ie:$(TARGET_COPY_OUT_VENDOR)/firmware/filter_ie \
    vendor/google/tangorpro/proprietary/vendor/firmware/focaltech_testconf.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_testconf.ini \
    vendor/google/tangorpro/proprietary/vendor/firmware/focaltech_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/fw_bcmdhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/fw_bcmdhd.map:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.map \
    vendor/google/tangorpro/proprietary/vendor/firmware/fw_bcmdhd_monitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd_monitor.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/google/edgetpu-janeiro.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/google/edgetpu-janeiro.fw \
    vendor/google/tangorpro/proprietary/vendor/firmware/google_wifi_firmware_config_info.pb:$(TARGET_COPY_OUT_VENDOR)/firmware/google_wifi_firmware_config_info.pb \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core0:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core0 \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core1:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core1 \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core2:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core2 \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core3:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core3 \
    vendor/google/tangorpro/proprietary/vendor/firmware/logstrs.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/logstrs.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mali_csffw-r52p0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw-r52p0.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mali_csffw-r53p0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw-r53p0.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mali_csffw-r54p0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw-r54p0.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mali_csffw-r54p1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw-r54p1.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_fw_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_csot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_mp_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp_csot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/readme_bottom.md:$(TARGET_COPY_OUT_VENDOR)/firmware/readme_bottom.md \
    vendor/google/tangorpro/proprietary/vendor/firmware/readme_top.md:$(TARGET_COPY_OUT_VENDOR)/firmware/readme_top.md \
    vendor/google/tangorpro/proprietary/vendor/firmware/sarconfig.info:$(TARGET_COPY_OUT_VENDOR)/firmware/sarconfig.info \
    vendor/google/tangorpro/proprietary/vendor/firmware/syna/BTFW.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/syna/BTFW.hcd \
    vendor/google/tangorpro/proprietary/vendor/firmware/syna/BTFW_B.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/syna/BTFW_B.hcd \
    vendor/google/tangorpro/proprietary/vendor/usr/idc/NVTCapacitivePen.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/NVTCapacitivePen.idc \
    vendor/google/tangorpro/proprietary/vendor/usr/idc/NVTCapacitiveTouchScreen.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/NVTCapacitiveTouchScreen.idc \
    vendor/google/tangorpro/proprietary/vendor/usr/idc/USI_Stylus.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/USI_Stylus.idc

PRODUCT_PACKAGES += \
    aoc_aud_ext \
    aoc_audio_stereo_spatializer \
    aocx-V2-ndk \
    arm.graphics-V1-ndk \
    audio_adapted_info_features \
    audio_amcs_ext \
    audio_apmg3_aoc \
    audio_bluenote_aoc \
    audio_bt_aoc \
    audio_cca_aoc \
    audio_fortemedia_aoc \
    audio_speech_enhancer_aoc \
    audio_spk_35l41 \
    audio_tunnel_aoc \
    audio_usb_aoc \
    audio_waves_aoc \
    com.google.edgetpu_app_service-V3-ndk_vendor \
    libGLES_mali \
    gxp_metrics_logger \
    audio.platform.aoc \
    audio.primary.gs201 \
    mapper.pixel \
    sound_trigger.primary.gs201 \
    vendor.google.whitechapel.audio.audioext@4.0-impl \
    vulkan.mali \
    libAlgFx_HiFi3z \
    libExynosC2ComponentStore \
    libExynosC2H263Dec \
    libExynosC2H263Enc \
    libExynosC2H264Dec \
    libExynosC2H264Enc \
    libExynosC2HevcDec \
    libExynosC2HevcEnc \
    libExynosC2Mpeg4Dec \
    libExynosC2Mpeg4Enc \
    libExynosC2Vp8Dec \
    libExynosC2Vp8Enc \
    libExynosC2Vp9Dec \
    libExynosC2Vp9Enc \
    libOpenCL-pixel \
    lib_aion_buffer \
    libacryl \
    libacryl_hdr_plugin \
    libadaptedinfo \
    libamcsextfile \
    libaoc \
    libaoctuningdecoder \
    libaocx \
    libbo_av1 \
    libc2filterplugin \
    libcast_auth \
    libcast_auth_aidl-cpp \
    libdisplaycolor \
    libedgetpu_client.google \
    libedgetpu_tachyon.google \
    libexynosutils \
    libexynosv4l2 \
    libfvsam_prm_parser \
    libgc2_av1_dec \
    libgc2_base \
    libgc2_cwl \
    libgc2_log \
    libgc2_store \
    libgc2_utils \
    libgpudataproducer \
    libhwjpeg \
    libion_google \
    libmahalcontroller \
    libmetrics_logger \
    libqorvo_uwb_params_nfcc \
    libsensorsuez \
    libspeechenhancer \
    libstreset21 \
    libsueznanoappclients \
    libusf \
    libvendorgraphicbuffer \
    sensors.usf \
    liboffloadeffect \
    libspatialaudio \
    vendor.google.battery_mitigation-V1-ndk \
    vendor.google.battery_mitigation.service_static \
    vendor.google.whitechapel.audio.audioext@4.0 \
    vendor.google.whitechapel.audio.extension-V5-ndk \
    android.hardware.authsecret-impl.nos \
    android.hardware.oemlock-impl.nos \
    android.hardware.power.stats-impl.gs-common \
    android.hardware.power.stats-impl.gs201 \
    android.hardware.security.keymint-impl.nos \
    android.hardware.weaver-bridge.nos \
    android.hardware.weaver-impl.nos \
    android.hardware.weaver2-impl.nos \
    aoc_aconfig_flags_c_lib \
    biometricsuez \
    com.fingerprints42.extension@1.0 \
    com.google.edgetpu.tachyon-ndk \
    com.google.edgetpu_vendor_service-V2-ndk_vendor \
    com.google.hardware.biometrics.parcelable.fingerprint.PressToAuthParcelable-V1-ndk \
    com.google.hardware.biometrics.sidefps.fingerprint-ext-V1-ndk \
    com.google.input-V2-ndk \
    com.google.input-V6-ndk \
    fake_gxp_telemetry_reader \
    fpc42_suez \
    fpc_util \
    gxp_telemetry_reader \
    android.hardware.graphics.allocator-aidl-impl \
    fingerprint.fpc \
    libExynosHWCService \
    lib_reader \
    lib_vendor_gsc_atoms \
    libalertv3 \
    libcodec2_soft_ddpdec \
    libcodec2_store_dolby \
    libdapparamstorage \
    libdarwinn_hal \
    libdeccfg \
    libdeeptouch \
    libdrmresource \
    libdump \
    libedgetpu_tflite_compiler \
    libedgetpu_util \
    libexynosdisplay \
    libgril_oem-google \
    libgxp \
    libmemtrack-pixel \
    libnos_citadeld_proxy \
    liboemcrypto \
    libpixelstats \
    libsit_oem \
    libsit_oem_proto \
    libspeech_waveformaec_runner \
    libtachyon_core \
    libtouchflow \
    modem_android_property_manager \
    modem_android_property_manager_impl \
    modem_log_constants \
    modem_log_dumper \
    sideFpsSuez \
    vendor-pixelatoms-cpp \
    vendor.google.audiometricext@1.0 \
    vendor.google.bluetooth_ext-V1-ndk \
    vendor.google.google_battery-V5-ndk \
    vendor_chre_atoms_log \
    vendor_chre_metrics-cpp \
    com.google.android.widevine-13130248 \
    com.google.pixel.camera.hal \
    com.google.pixel.wifi.ext \
    HardwareInfo \
    com.google.android.camera.experimental2022 \
    android.hardware.authsecret-service.citadel.xml \
    android.hardware.camera.provider@2.7-service-google-apex.xml \
    android.hardware.contexthub-service.generic.xml \
    android.hardware.dumpstate.3-service.xml \
    android.hardware.neuralnetworks@service-darwinn-aidl.xml \
    android.hardware.oemlock-service.citadel.xml \
    android.hardware.security.keymint-service.citadel.xml \
    android.hardware.weaver-service.citadel.xml \
    fingerprint-fpc42.xml \
    hwc3-default.xml \
    manifest.xml \
    manifest_android.hardware.drm-service.castkey.xml \
    manifest_aocx.xml \
    manifest_gralloc_aidl2.xml \
    manifest_input.processor-service.xml \
    manifest_radioext.xml \
    memtrack.xml \
    pixel-display-default.xml \
    qorvo.uwb-service.xml \
    vendor.dolby.media.c2@1.0-service.xml \
    vendor.google.battery_mitigation-default.xml \
    vendor.google.edgetpu_vendor_service@1.0-service.xml \
    vendor.google.google_battery-default.xml \
    aocd \
    aocxd \
    dump_aoc \
    dump_devfreq \
    dump_exynos_display \
    dump_fingerprint \
    dump_gsc \
    dump_modemlog \
    dump_perf \
    dump_pixel_metrics \
    dump_power \
    dump_sensors \
    dump_soc \
    dump_storage \
    dump_thermal \
    dump_touch \
    dump_trusty \
    dump_umfw_stat \
    predump_gti0 \
    android.hardware.authsecret-service.citadel \
    android.hardware.biometrics.fingerprint-service.fpc42 \
    android.hardware.bluetooth@1.1-service.synabtlinux \
    android.hardware.composer.hwc3-service.pixel \
    android.hardware.contexthub-service.generic \
    android.hardware.drm-service.castkey \
    android.hardware.dumpstate.3-service \
    android.hardware.edgetpu.logging@service-edgetpu-logging \
    android.hardware.graphics.allocator-V2-service \
    android.hardware.gxp.logging@service-gxp-logging \
    android.hardware.input.processor-service \
    android.hardware.memtrack-service.pixel \
    android.hardware.neuralnetworks@service-darwinn-aidl \
    android.hardware.oemlock-service.citadel \
    android.hardware.power.stats-service.pixel \
    android.hardware.qorvo.uwb.service \
    android.hardware.security.keymint-service.citadel \
    android.hardware.weaver-service.citadel \
    battery_mitigation \
    citadel_updater \
    citadeld \
    com.google.edgetpu.tachyon-service \
    disable_contaminant_detection \
    google.hardware.media.c2@1.0-service \
    init_citadel \
    samsung.hardware.media.c2@1.2-service \
    vendor.dolby.media.c2@1.0-service \
    vendor.google.audiometricext@1.0-service-vendor \
    vendor.google.edgetpu_vendor_service@1.0-service \
    vendor.google.google_battery-service \
    vendor.google.radioext@1.0-service \
    init.camera.set-interrupts-ownership \
    init.display \
    init.uwb.calib \
    insmod \
    pixelstats-vendor \
    predump_touch \
    sscoredump \
    touch_gti_ical \
    trusty_metricsd \
    twoshay \
    ufs_firmware_update \
    umfw_stat_tool \
    usf_stats
