#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/tangorpro

PRODUCT_COPY_FILES += \
    vendor/google/tangorpro/proprietary/product/etc/ambient/matcher_tah.leveldb:$(TARGET_COPY_OUT_PRODUCT)/etc/ambient/matcher_tah.leveldb \
    vendor/google/tangorpro/proprietary/product/etc/appcompat/compat_framework_overrides.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/appcompat/compat_framework_overrides.xml \
    vendor/google/tangorpro/proprietary/product/etc/default-permissions/default-permissions_SmartDisplayPrebuilt.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permissions_SmartDisplayPrebuilt.xml \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.descriptor:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.descriptor \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.sound_model:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.sound_model \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.sound_model_2:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.sound_model_2 \
    vendor/google/tangorpro/proprietary/product/etc/firmware/music_detector.sound_model_tflite:$(TARGET_COPY_OUT_PRODUCT)/etc/firmware/music_detector.sound_model_tflite \
    vendor/google/tangorpro/proprietary/product/etc/permissions/androidx.camera.extensions.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/androidx.camera.extensions.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.android.apps.mediashell.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.apps.mediashell.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.android.apps.nest.castauth.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.apps.nest.castauth.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.android.apps.nest.dockmanager.app.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.apps.nest.dockmanager.app.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.android.hardwareinfo.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.hardwareinfo.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.assistant.hubui.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.assistant.hubui.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.pixel.camera.connectivity.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.pixel.camera.connectivity.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.pixel.camera.services.cameraidremapper.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.pixel.camera.services.cameraidremapper.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.impl.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.impl.xml \
    vendor/google/tangorpro/proprietary/product/etc/permissions/privapp-permissions-google-p-lineage.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google-p-lineage.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/GoogleCamera_6gb_or_more_ram.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/GoogleCamera_6gb_or_more_ram.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/communal.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/communal.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/google-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-hiddenapi-package-whitelist.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/google-nest-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-nest-hiddenapi-package-whitelist.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/kids_home_experience.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/kids_home_experience.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/nexus.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/nexus.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_docking_experience_2022.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_docking_experience_2022.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2017.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2017.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2018.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2018.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2019.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2019.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2019_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2019_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2020.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2020.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2020_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2020_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2021.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2021.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2021_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2021_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2022.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2022.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_experience_2022_midyear.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2022_midyear.xml \
    vendor/google/tangorpro/proprietary/product/etc/sysconfig/pixel_tablet_experience_2023.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_tablet_experience_2023.xml \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw.bin \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_csot.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_csot.bin \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp.bin \
    vendor/google/tangorpro/proprietary/recovery/root/vendor/firmware/novatek_ts_mp_csot.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp_csot.bin \
    vendor/google/tangorpro/proprietary/system_ext/etc/init/vendor.google.edgetpu_app_service@1.0-service.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/vendor.google.edgetpu_app_service@1.0-service.rc \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.android.camera.extensions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.android.camera.extensions.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.android.camerax.extensions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.android.camerax.extensions.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.pixel.camera.connectivity.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.pixel.camera.connectivity.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.pixel.camera.services.cameraidremapper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.pixel.camera.services.cameraidremapper.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.google.pixel.camera.services.lyricconfigprovider.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/google-ril.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/google-ril.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/privapp-permissions-google-se-lineage.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-google-se-lineage.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/permissions/privapp-permissions-qorvo.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-qorvo.xml \
    vendor/google/tangorpro/proprietary/system_ext/etc/public.libraries-google.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/public.libraries-google.txt

PRODUCT_PACKAGES += \
    com.google.edgetpu_app_service-V3-ndk \
    com.google.edgetpu_vendor_service-V2-ndk \
    libhbmsvmanager_jni \
    AndroidMediaShell \
    CastAuthPrebuilt \
    DeviceIntelligenceNetworkPrebuilt-bfinal_astrea_20250217.00_RC00 \
    DevicePersonalizationPrebuiltPixelTablet2023-bfinal_aiai_20250217.00_RC08 \
    DockManagerPrebuilt \
    HardwareInfo \
    HomegraphPrebuilt \
    HotwordEnrollmentOKGoogleFUSIONPro \
    HotwordEnrollmentXGoogleFUSIONPro \
    PixelCameraServices \
    SmartDisplayPrebuilt \
    UsoniaPrebuilt \
    PersistentBackgroundCameraServices \
    ConnectivityThermalPowerManager \
    DockSetup \
    HbmSVManager \
    UwbVendorService \
    grilservice \
    libhwinfo \
    com.android.hotwordenrollment.common.util \
    com.google.android.camera.extensions \
    com.google.android.camerax.extensions \
    com.google.pixel.camera.connectivity \
    com.google.pixel.camera.services.cameraidremapper \
    com.google.pixel.camera.services.lyricconfigprovider \
    google-ril \
    com.google.pixel.camera.services@1.0-service-google.xml \
    vendor.google.edgetpu_app_service@1.0-service.xml \
    vendor.google.edgetpu_app_service@1.0-service

PRODUCT_PACKAGES += \
    system_ext_priv-app_HbmSVManager_lib_arm64_libhbmsvmanager_jni_so

PRODUCT_COPY_FILES += \
    vendor/google/tangorpro/proprietary/vendor/etc/Khronos/OpenCL/vendors/ARM.icd:$(TARGET_COPY_OUT_VENDOR)/etc/Khronos/OpenCL/vendors/ARM.icd \
    vendor/google/tangorpro/proprietary/vendor/etc/aoc/waveform_aec_graph.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/aoc/waveform_aec_graph.tflite \
    vendor/google/tangorpro/proprietary/vendor/etc/atc_profile.json:$(TARGET_COPY_OUT_VENDOR)/etc/atc_profile.json \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/activity.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/activity.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/activity.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/activity.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/ambient_volume.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ambient_volume.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/ambient_volume.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/ambient_volume.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/capo.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/capo.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/capo.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/capo.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/drop.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/drop.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/drop.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/drop.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/health.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/health.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/health.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/health.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/imu_cal.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/imu_cal.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/imu_cal.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/imu_cal.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/libchre_log_database.bin:$(TARGET_COPY_OUT_VENDOR)/etc/chre/libchre_log_database.bin \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/motiondetector.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/motiondetector.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/motiondetector.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/motiondetector.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/sd.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sd.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/sd.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/sd.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/system_signal_hub.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/system_signal_hub.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/system_signal_hub.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/system_signal_hub.so \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/uv_exposure.napp_header:$(TARGET_COPY_OUT_VENDOR)/etc/chre/uv_exposure.napp_header \
    vendor/google/tangorpro/proprietary/vendor/etc/chre/uv_exposure.so:$(TARGET_COPY_OUT_VENDOR)/etc/chre/uv_exposure.so \
    vendor/google/tangorpro/proprietary/vendor/etc/display_settings.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display_settings.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/displayconfig/display_id_4619827677550801152.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4619827677550801152.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/init/Exynos_C2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/Exynos_C2.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.authsecret-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.authsecret-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service.synabtlinux.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service.synabtlinux.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.camera.provider@2.7-service-google-apex.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.7-service-google-apex.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.contexthub-service.generic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.contexthub-service.generic.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.drm-service.castkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.castkey.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.edgetpu.logging@service-edgetpu-logging.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.edgetpu.logging@service-edgetpu-logging.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.graphics.allocator2-aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator2-aidl-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.gxp.logging@service-gxp-logging.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gxp.logging@service-gxp-logging.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.input.processor-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.input.processor-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.neuralnetworks@service-darwinn-aidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@service-darwinn-aidl.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.oemlock-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.oemlock-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.rlsservice-service-google-apex.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.rlsservice-service-google-apex.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.security.keymint-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/android.hardware.weaver-service.citadel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.weaver-service.citadel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/aocd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/aocd.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/aocxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/aocxd.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/citadeld.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/citadeld.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/com.google.edgetpu.tachyon-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.google.edgetpu.tachyon-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/fingerprint-fpc42.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fingerprint-fpc42.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/google.hardware.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/google.hardware.media.c2@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/hwc3-pixel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hwc3-pixel.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.camera.set-interrupts-ownership.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.camera.set-interrupts-ownership.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.sscoredump.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sscoredump.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init.usf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.usf.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/init_dauntless.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_dauntless.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/memtrack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/pixelstats-vendor.gs201.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pixelstats-vendor.gs201.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/qorvo.uwb-calib.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qorvo.uwb-calib.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/qorvo.uwb-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qorvo.uwb-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/samsung.hardware.media.c2@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/samsung.hardware.media.c2@1.2-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/trusty_metricsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusty_metricsd.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/twoshay.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/twoshay.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.dolby.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.audiometricext@1.0-service-vendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.audiometricext@1.0-service-vendor.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.battery_mitigation-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.battery_mitigation-default.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.edgetpu_vendor_service@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.edgetpu_vendor_service@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.google_battery-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.google_battery-default.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/init/vendor.google.radioext@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.google.radioext@1.0-service.rc \
    vendor/google/tangorpro/proprietary/vendor/etc/input_classifier_model.pb:$(TARGET_COPY_OUT_VENDOR)/etc/input_classifier_model.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs_aosp_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_aosp_c2.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/media_codecs_dolby_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_c2.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/modem_stat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/modem_stat.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/permissions/android.hardware.strongbox_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.strongbox_keystore.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/permissions/com.google.android.camera.experimental2022.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.google.android.camera.experimental2022.xml \
    vendor/google/tangorpro/proprietary/vendor/etc/pixelstats_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/pixelstats_config.json \
    vendor/google/tangorpro/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/google/tangorpro/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base.policy \
    vendor/google/tangorpro/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext.policy \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/device_cal_info:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/device_cal_info \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/append/motion_state.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/append/motion_state.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/append/power.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/append/power.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/tangorpro_black.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/tangorpro_black.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/sensors/registry/tangorpro_white.reg:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/tangorpro_white.reg \
    vendor/google/tangorpro/proprietary/vendor/etc/touchflow.pb:$(TARGET_COPY_OUT_VENDOR)/etc/touchflow.pb \
    vendor/google/tangorpro/proprietary/vendor/etc/twoshay_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/twoshay_config.json \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/calib_paths:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/calib_paths \
    vendor/google/tangorpro/proprietary/vendor/etc/uwb/libuwb-uci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uwb/libuwb-uci.conf \
    vendor/google/tangorpro/proprietary/vendor/firmware/1540.app:$(TARGET_COPY_OUT_VENDOR)/firmware/1540.app \
    vendor/google/tangorpro/proprietary/vendor/firmware/aoc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aoc.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/bcmdhd.cal:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd.cal \
    vendor/google/tangorpro/proprietary/vendor/firmware/bcmdhd_clm.blob:$(TARGET_COPY_OUT_VENDOR)/firmware/bcmdhd_clm.blob \
    vendor/google/tangorpro/proprietary/vendor/firmware/cast_auth.app:$(TARGET_COPY_OUT_VENDOR)/firmware/cast_auth.app \
    vendor/google/tangorpro/proprietary/vendor/firmware/dauntless/d3m2.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dauntless/d3m2.ec.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/dauntless/evt.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dauntless/evt.ec.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/dauntless/proto11.ec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dauntless/proto11.ec.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/filter_ie:$(TARGET_COPY_OUT_VENDOR)/firmware/filter_ie \
    vendor/google/tangorpro/proprietary/vendor/firmware/focaltech_testconf.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_testconf.ini \
    vendor/google/tangorpro/proprietary/vendor/firmware/focaltech_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/fw_bcmdhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/fw_bcmdhd.map:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.map \
    vendor/google/tangorpro/proprietary/vendor/firmware/fw_bcmdhd_monitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd_monitor.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/google/edgetpu-janeiro.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/google/edgetpu-janeiro.fw \
    vendor/google/tangorpro/proprietary/vendor/firmware/google_wifi_firmware_config_info.pb:$(TARGET_COPY_OUT_VENDOR)/firmware/google_wifi_firmware_config_info.pb \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core0:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core0 \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core1:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core1 \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core2:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core2 \
    vendor/google/tangorpro/proprietary/vendor/firmware/gxp_fw_core3:$(TARGET_COPY_OUT_VENDOR)/firmware/gxp_fw_core3 \
    vendor/google/tangorpro/proprietary/vendor/firmware/logstrs.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/logstrs.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mali_csffw-r52p0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw-r52p0.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mali_csffw-r53p0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw-r53p0.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mali_csffw-r54p0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw-r54p0.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_fw_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_csot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/novatek_ts_mp_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp_csot.bin \
    vendor/google/tangorpro/proprietary/vendor/firmware/sarconfig.info:$(TARGET_COPY_OUT_VENDOR)/firmware/sarconfig.info \
    vendor/google/tangorpro/proprietary/vendor/firmware/syna/BTFW.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/syna/BTFW.hcd \
    vendor/google/tangorpro/proprietary/vendor/firmware/syna/BTFW_B.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/syna/BTFW_B.hcd

PRODUCT_PACKAGES += \
    aoc_aud_ext \
    aoc_audio_stereo_spatializer \
    aocx-V2-ndk \
    arm.graphics-V1-ndk \
    audio_adapted_info_features \
    audio_amcs_ext \
    audio_apmg3_aoc \
    audio_bluenote_aoc \
    audio_bt_aoc \
    audio_cca_aoc \
    audio_fortemedia_aoc \
    audio_speech_enhancer_aoc \
    audio_spk_35l41 \
    audio_tunnel_aoc \
    audio_usb_aoc \
    audio_waves_aoc \
    com.google.edgetpu_app_service-V3-ndk_vendor \
    libGLES_mali \
    gxp_metrics_logger \
    audio.platform.aoc \
    audio.primary.gs201 \
    mapper.pixel \
    sound_trigger.primary.gs201 \
    vendor.google.whitechapel.audio.audioext@4.0-impl \
    vulkan.mali \
    libAlgFx_HiFi3z \
    libExynosC2ComponentStore \
    libExynosC2H263Dec \
    libExynosC2H263Enc \
    libExynosC2H264Dec \
    libExynosC2H264Enc \
    libExynosC2HevcDec \
    libExynosC2HevcEnc \
    libExynosC2Mpeg4Dec \
    libExynosC2Mpeg4Enc \
    libExynosC2Vp8Dec \
    libExynosC2Vp8Enc \
    libExynosC2Vp9Dec \
    libExynosC2Vp9Enc \
    libOpenCL-pixel \
    lib_aion_buffer \
    libacryl \
    libacryl_hdr_plugin \
    libadaptedinfo \
    libamcsextfile \
    libaoc \
    libaoctuningdecoder \
    libaocx \
    libbo_av1 \
    libc2filterplugin \
    libcast_auth \
    libcast_auth_aidl-cpp \
    libdisplaycolor \
    libedgetpu_client.google \
    libedgetpu_tachyon.google \
    libexynosutils \
    libexynosv4l2 \
    libfvsam_prm_parser \
    libgc2_av1_dec \
    libgc2_base \
    libgc2_cwl \
    libgc2_log \
    libgc2_store \
    libgc2_utils \
    libgpudataproducer \
    libhwjpeg \
    libion_google \
    libmahalcontroller \
    libmetrics_logger \
    libqorvo_uwb_params_nfcc \
    libsensorsuez \
    libspeechenhancer \
    libstreset21 \
    libsueznanoappclients \
    libusf \
    libvendorgraphicbuffer \
    sensors.usf \
    liboffloadeffect \
    libspatialaudio \
    vendor.google.battery_mitigation-V1-ndk \
    vendor.google.battery_mitigation.service_static \
    vendor.google.whitechapel.audio.audioext@4.0 \
    vendor.google.whitechapel.audio.extension-V5-ndk \
    android.hardware.authsecret-impl.nos \
    android.hardware.oemlock-impl.nos \
    android.hardware.security.keymint-impl.nos \
    android.hardware.weaver-bridge.nos \
    android.hardware.weaver-impl.nos \
    android.hardware.weaver2-impl.nos \
    aoc_aconfig_flags_c_lib \
    biometricsuez \
    com.fingerprints42.extension@1.0 \
    com.google.edgetpu.tachyon-ndk \
    com.google.edgetpu_vendor_service-V2-ndk_vendor \
    com.google.hardware.biometrics.parcelable.fingerprint.PressToAuthParcelable-V1-ndk \
    com.google.hardware.biometrics.sidefps.fingerprint-ext-V1-ndk \
    com.google.input-V2-ndk \
    com.google.input-V6-ndk \
    fake_gxp_telemetry_reader \
    fpc42_suez \
    fpc_util \
    gxp_telemetry_reader \
    android.hardware.graphics.allocator-aidl-impl \
    fingerprint.fpc \
    libExynosHWCService \
    lib_reader \
    libcodec2_soft_ddpdec \
    libcodec2_store_dolby \
    libdapparamstorage \
    libdarwinn_hal \
    libdeccfg \
    libdeeptouch \
    libdrmresource \
    libedgetpu_tflite_compiler \
    libedgetpu_util \
    libexynosdisplay \
    libgril_oem-google \
    libgxp \
    libmemtrack-pixel \
    libnos_citadeld_proxy \
    liboemcrypto \
    libpixelstats \
    libsit_oem \
    libsit_oem_proto \
    libspeech_waveformaec_runner \
    libtachyon_core \
    libtouchflow \
    sideFpsSuez \
    vendor-pixelatoms-cpp \
    vendor.google.audiometricext@1.0 \
    vendor.google.bluetooth_ext-V1-ndk \
    vendor.google.google_battery-V4-ndk \
    vendor_chre_atoms_log \
    vendor_chre_metrics-cpp \
    com.google.android.widevine-13130248 \
    com.google.pixel.camera.hal \
    com.google.pixel.wifi.ext \
    com.google.android.camera.experimental2022 \
    android.hardware.authsecret-service.citadel.xml \
    android.hardware.camera.provider@2.7-service-google-apex.xml \
    android.hardware.contexthub-service.generic.xml \
    android.hardware.neuralnetworks@service-darwinn-aidl.xml \
    android.hardware.oemlock-service.citadel.xml \
    android.hardware.security.keymint-service.citadel.xml \
    android.hardware.weaver-service.citadel.xml \
    fingerprint-fpc42.xml \
    hwc3-default.xml \
    manifest.xml \
    manifest_android.hardware.drm-service.castkey.xml \
    manifest_aocx.xml \
    manifest_gralloc_aidl2.xml \
    manifest_input.processor-service.xml \
    manifest_radioext.xml \
    memtrack.xml \
    pixel-display-default.xml \
    qorvo.uwb-service.xml \
    vendor.dolby.media.c2@1.0-service.xml \
    vendor.google.battery_mitigation-default.xml \
    vendor.google.edgetpu_vendor_service@1.0-service.xml \
    vendor.google.google_battery-default.xml \
    aocd \
    aocxd \
    android.hardware.authsecret-service.citadel \
    android.hardware.biometrics.fingerprint-service.fpc42 \
    android.hardware.bluetooth@1.1-service.synabtlinux \
    android.hardware.composer.hwc3-service.pixel \
    android.hardware.contexthub-service.generic \
    android.hardware.drm-service.castkey \
    android.hardware.edgetpu.logging@service-edgetpu-logging \
    android.hardware.graphics.allocator-V2-service \
    android.hardware.gxp.logging@service-gxp-logging \
    android.hardware.input.processor-service \
    android.hardware.memtrack-service.pixel \
    android.hardware.neuralnetworks@service-darwinn-aidl \
    android.hardware.oemlock-service.citadel \
    android.hardware.qorvo.uwb.service \
    android.hardware.security.keymint-service.citadel \
    android.hardware.weaver-service.citadel \
    battery_mitigation \
    citadel_updater \
    citadeld \
    com.google.edgetpu.tachyon-service \
    google.hardware.media.c2@1.0-service \
    init_citadel \
    samsung.hardware.media.c2@1.2-service \
    vendor.dolby.media.c2@1.0-service \
    vendor.google.audiometricext@1.0-service-vendor \
    vendor.google.edgetpu_vendor_service@1.0-service \
    vendor.google.google_battery-service \
    vendor.google.radioext@1.0-service \
    init.camera.set-interrupts-ownership \
    pixelstats-vendor \
    sscoredump \
    trusty_metricsd \
    twoshay \
    umfw_stat_tool \
    usf_stats
